### ISSUE TITLE
[BE] Criar rotinas de testes

### ISSUE THREAD

**Issue by ruiblaese** [codenation-dev/squad-6-aceleradev-fs-online-1#1]
Criar rotinas de testes para todas as rotas

Exemplo:
https://github.com/ricardolonga/goteca/blob/simple_code/movies_test.go

Acredito que fica legal se fizermos um arquivo de teste para cada grupo de rota, exemplo: "user", "customer", etc

**Comment by marcopollivier** [comment]
Tem uns artigos bem bacanas sobre TDD que de repente ajude vocês nessa tarefa 

https://medium.com/@sheimyrahman/golang-go-e-tdd-para-iniciantes-2418b6eadd92
https://medium.com/@pierreprinetti/test-driven-development-in-go-baeab5adb468

E esse projeto aqui ajuda bastante na prática também 

https://github.com/quii/learn-go-with-tests
