### ISSUE TITLE
criar método de login e autenticação do usuário backend

### ISSUE THREAD

**Issue by cpereiramt** [codenation-dev/squad-6-aceleradev-fs-online-1#10]
Criar o login e autenticação do usuário .

**Comment by ruiblaese** [comment]
Lembrando\Ressaltando que foi criado uma nova pasta "frontend" onde pode ser colocado nosso projeto em react

**Comment by ruiblaese** [comment]
@cpereiramt quando criou essa issue pensou na camada cliente ou servidor?

Existe método de login na camada servidor, acho que as novas issues podemos dividir em backend e frontend, podemos colocar na frente da descrição da issue.

API Backend, rota: Login: http://localhost:3000/api/v1/signin

**Comment by cpereiramt** [comment]
Vai ser no backend mesmo, coloquei informações incompletas .

**Comment by ruiblaese** [comment]
rotina pronta, rota de login com retorno do token funcionando faz alguns dias ja

![image](https://user-images.githubusercontent.com/12955543/58752876-a6309380-848c-11e9-8cd5-2096f2891053.png)
