### ISSUE TITLE
request para rota /users retorna 401 no Frontend 

### ISSUE THREAD

**Issue by cpereiramt** [codenation-dev/squad-6-aceleradev-fs-online-1#17]
Foi feita a autenticação no login /api/v1/signup e já está autenticando corretamente, retornando status 200 do servidor, restando a rota /api/v1/users que por algum motivo retorna status 204 no Log do Gin e no console do navegador retorna 401  .

**Comment by ruiblaese** [comment]
@cpereiramt resolvido de verdade agora

**Comment by ruiblaese** [comment]
se possível tens como testar? acredito que agora vai funcionar tudo 100%

![image](https://user-images.githubusercontent.com/12955543/59151568-c66fcd80-8a0b-11e9-8989-2633bccc1bc0.png)
