### ISSUE TITLE
[FE] Formulário para importação de Arquivo CSV (Estrutura)

### ISSUE THREAD

**Issue by cpereiramt** [codenation-dev/squad-6-aceleradev-fs-online-1#22]
Tela para importação de informações em formato de arquivo CSV .

**Comment by ruiblaese** [comment]
Como combinamos, junto com esse chamado vamos fazer cadastro manual de cliente. Onde pode ser editado e cadastrado.

Essas funcionalidades podem ser baseadas nas rotas e rotinas do Usuario

**Comment by ruiblaese** [comment]
No formulario cadastro\edicao de clientes acho legal mostrarmos um histórico de pagamentos.
Estou fazendo uma rota no backend para isso.

**Comment by ruiblaese** [comment]
nova issue criada para tarefas citadas acima #37
