### ISSUE TITLE
[FE] Tela manutenção de clientes não está carregando

### ISSUE THREAD

**Issue by cpereiramt** [codenation-dev/squad-6-aceleradev-fs-online-1#43]
#42 Tela de cadastrar cliente não está carregando, apesar de já ter configurado a rota, e de quando clico no botão Novo cliente ou editar mudar a url para http://localhost:3000/customer/ e http://localhost:3000/customer/1 respectivamente o component não é renderizado, permanecendo a lista de todos clientes .

**Comment by ruiblaese** [comment]
apenas olhando pelo github não encontrei o problema, fiz o pull request e hoje a noite vou puxar o código para ver na pratica o que está acontecendo.

**Comment by ruiblaese** [comment]
apenas olhando pelo github não encontrei o problema, fiz o pull request e hoje a noite vou puxar o código para ver na pratica o que está acontecendo.

**Comment by ruiblaese** [comment]
apenas olhando pelo github não encontrei o problema, fiz o pull request e hoje a noite vou puxar o código para ver na pratica o que está acontecendo.

**Comment by ruiblaese** [comment]
apenas olhando pelo github não encontrei o problema, hoje a noite vou puxar o código para ver na pratica o que está acontecendo.

**Comment by cpereiramt** [comment]
resolvido, faltava alterar o import no component App.js
