### ISSUE TITLE
[FE] Criar filtros tela detalhes do alerta

### ISSUE THREAD

**Issue by cpereiramt** [codenation-dev/squad-6-aceleradev-fs-online-1#47]
Acrescentar os campos " usuario que envio email",  "cliente que recebeu o alerta" e quantas "vezes que os alertas foram enviados"  para um determinado cliente cliente . #46

**Comment by ruiblaese** [comment]
Opa,

Favor ler escopo do trabalho, talvez eu tenha entendido errado: https://github.com/codenation-dev/squad-6-aceleradev-fs-online-1/blob/master/README.md

Pelo que eu entendo:
- não existe isso de usuário que enviou e-mail, e-mail é enviado pelo sistema para o Usuário.
- alerta não é enviado para cliente, então não existe essa de quantas vezes o cliente recebeu alerta.
- "vezes que os alertas foram enviados" -> tenho que analisar isso, mas teoricamente alerta é para ser enviado apenas uma vez.

Acredito que o certo para essa tela de histórico de alerta seriam filtros:
 - por usuário
 - por pagamento

**Comment by cpereiramt** [comment]
ok, entendido, então vou implementar os filtros para a tela .

**Comment by ruiblaese** [comment]
resolvido em https://github.com/codenation-dev/squad-6-aceleradev-fs-online-1/commit/3d69ea3668fcc6af69c2f2ace2341c308c25256e
